sudo: required

services: 
  - docker

before_install:
  - npm run migrate:clean && docker build -t posm-paths .

script:
  - docker run posm-paths /bin/bash -c 'npm install --build-from-sources && SPATIALITE_LOCATION=/usr/lib/x86_64-linux-gnu ENVIRONMENT=test npm run test'
